### ISSUE TITLE
No Anki Template

### ISSUE THREAD

**Issue by gentlegiant1972** [mnemosyne-proj/mnemosyne#169] opened 2020-08-13 01:51 UTC
Attempting to make the file from git generates the following error: 

Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/bin/mnemosyne", line 268, in <module>
    mnemosyne.initialise(data_dir=data_dir, filename=filename,
  File "/usr/lib/python3.8/site-packages/mnemosyne/libmnemosyne/__init__.py", line 397, in initialise
    self.register_components()
  File "/usr/lib/python3.8/site-packages/mnemosyne/libmnemosyne/__init__.py", line 464, in register_components
    component = component(component_manager=self.component_manager)
  File "/usr/lib/python3.8/site-packages/mnemosyne/libmnemosyne/card_types/M_sided.py", line 36, in __init__
    from mnemosyne.libmnemosyne.renderers.anki_renderer import AnkiRenderer
  File "/usr/lib/python3.8/site-packages/mnemosyne/libmnemosyne/renderers/anki_renderer.py", line 10, in <module>
    from mnemosyne.libmnemosyne.renderers.anki.template import render as _render
  File "/usr/lib/python3.8/site-packages/mnemosyne/libmnemosyne/renderers/anki/template/__init__.py", line 1, in <module>
    from anki.template.template import Template
 ModuleNotFoundError: No module named 'anki.template.template'; 'anki.template' is not a package

My system: Linux 5.7.9-1-MANJARO #1 SMP PREEMPT

Building from the AUR works, but it won't launch, and running it from the terminal gives the same *ModuleNotFoundError: No module named 'anki.template.template'; 'anki.template' is not a package*

**Comment by pbienst** [comment] 2020-08-13 11:31
I'm afraid I cannot reproduce this on a fresh checkout (Windows cygwin, Python 3.7). 

Are you sure mnemosyne\libmnemosyne\renderers\anki\template\template.py exists in your system?

**Comment by pbienst** [comment] 2020-08-13 11:34
Another thing to try is change the top of template/init.py

from
```
from anki.template.template import Template
from anki.template.view import View
```
to

```
from .template import Template
from .view import View
```

**Comment by pbienst** [comment] 2020-08-20 12:23
I've committed the above change to the repository. Please reopen if you have any more issues.

**Closed by pbienst** 2020-08-20 12:23 UTC
