### ISSUE TITLE
Unable to search cards

### ISSUE THREAD

**Issue by marmistrz** [mnemosyne-proj/mnemosyne#97] opened 2018-11-01 07:15 UTC
The following exception occurs and makes it completely impossible to filter cards in the browse view:
```
Traceback (innermost last):
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/browse_cards_dlg.py", line 856, in update_filter
    self.update_card_counters()
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/browse_cards_dlg.py", line 876, in update_card_counters
    _("%d cards shown, of which %d active.") % (selected, active))
 TypeError: %d format: a number is required, not NoneType
```

The error happens on both 2.6 and 2.6.1. If I comment out the affected line, I get no results for the search.

Such errors could be avoided if optional typing were used :))

**Comment by pbienst** [comment] 2018-11-01 10:09
I cannot reproduce this... Does it also occur if you start from a fresh database?

Note: I still use Python 3.6 though.

**Comment by marmistrz** [comment] 2018-11-01 14:51
I'm using Python 3.7.1 on Arch Linux. It doesn't occur on a fresh database. It is consistent across two Arch systems.
I sent you the affected database by e-mail.

**Comment by marmistrz** [comment] 2018-11-05 23:17
It looks like the SQL query fails:
```
Warning: Could not import OpenGL. Might cause a black screen on some Linux distributions. Try installing python3-opengl in that case.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
Log body:
 An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/browse_cards_dlg.py", line 856, in update_filter
    self.update_card_counters()
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/browse_cards_dlg.py", line 876, in update_card_counters
    _("%d cards shown, of which %d active.") % (selected, active))
 TypeError: %d format: a number is required, not NoneType

An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/browse_cards_dlg.py", line 856, in update_filter
    self.update_card_counters()
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/browse_cards_dlg.py", line 876, in update_card_counters
    _("%d cards shown, of which %d active.") % (selected, active))
 TypeError: %d format: a number is required, not NoneType
```

**Comment by pbienst** [comment] 2018-11-06 04:43
Sorry for not yet having had time to look at this, I'm a bit swamped. I've seen this before, though, there's probably a corrupt card in your database due to some old bug which should have been fixed.

**Comment by pbienst** [comment] 2018-11-06 05:11
O, forgot : does running compact database help.?

**Comment by marmistrz** [comment] 2018-11-06 08:11
Yes, it helped, but I wasn't able to cleanly quit Mnemosyne after compact. I had to kill the process.
```
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
b'Waiting for uploader thread to stop...'
b'Done!'
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
QIODevice::write (QProcess): device not open
Log body:
 An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/main_wdgt.py", line 239, in browse_cards
    self.controller().show_browse_cards_dialog()
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/controllers/default_controller.py", line 827, in show_browse_cards_dialog
    review_controller.reset_but_try_to_keep_current_card()
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/review_controllers/SM2_controller.py", line 72, in reset_but_try_to_keep_current_card
    sch.rebuild_queue()
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/schedulers/SM2_mnemosyne.py", line 215, in rebuild_queue
    if not db.is_loaded() or not db.active_count():
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/databases/SQLite_statistics.py", line 42, in active_count
    where active=1""").fetchone()[0]
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/databases/_sqlite3.py", line 72, in execute
    self._cursor = self.connection.execute(sql, *args)
 sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140356007831296 and this is thread id 140356829791744.

An unexpected error has occurred.
Please forward the following info to the developers:

Traceback (innermost last):
  File "/usr/lib/python3.7/site-packages/mnemosyne/pyqt_ui/main_wdgt.py", line 239, in browse_cards
    self.controller().show_browse_cards_dialog()
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/controllers/default_controller.py", line 827, in show_browse_cards_dialog
    review_controller.reset_but_try_to_keep_current_card()
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/review_controllers/SM2_controller.py", line 72, in reset_but_try_to_keep_current_card
    sch.rebuild_queue()
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/schedulers/SM2_mnemosyne.py", line 215, in rebuild_queue
    if not db.is_loaded() or not db.active_count():
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/databases/SQLite_statistics.py", line 42, in active_count
    where active=1""").fetchone()[0]
  File "/usr/lib/python3.7/site-packages/mnemosyne/libmnemosyne/databases/_sqlite3.py", line 72, in execute
    self._cursor = self.connection.execute(sql, *args)
 sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140356007831296 and this is thread id 140356829791744.
```

**Comment by pbienst** [comment] 2018-11-06 10:34
The final error is due to some hard-to-reproduce race condition. Feel free to make a separate bug report about it if you want, but I'm closing this report since the original problem has been solved.

**Closed by pbienst** 2018-11-06 10:34 UTC
