### ISSUE TITLE
Trace Back Error

### ISSUE THREAD

**Issue by boucher9** [mnemosyne-proj/mnemosyne#46] opened 2018-03-23 01:41 UTC
This is a great product which I have been using as I prepare for O & Ps. The error does not seem to occur when near the beginning of the database, but as I get in past the first 200 cards or so.... the problem crops up. I'll edit the card as normal, then hit page down or next card or previous card and this error pops up. I have somewhere close to 1350 cards, 1220 are active. Thank you. Keep up the great work !
![tracebackerror](https://user-images.githubusercontent.com/5243957/37806901-94e05166-2e10-11e8-8ec1-e4f1bcf5ed49.jpg)

**Comment by pbienst** [comment] 2018-03-23 08:05
Duplicate of #8

**Comment by pbienst** [comment] 2018-03-23 08:06
See issue 8, but if you have a recipe that allows you to reproduce the bug, that would be helpful.

**Closed by pbienst** 2018-03-23 08:06 UTC
